server:
  port: 1081

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 554052234273-se9acbvqso7fukjvfcg6cbn085snl8ka.apps.googleusercontent.com
            client-secret: DdGenAs4Q2SsVQEX8PVDcOWO
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  datasource:
    url: jdbc:postgresql://localhost:5432/wfrp
    username: wfrp
    password: wfrp
    driver-class-name: org.postgresql.Driver
#  cloud:
#    gcp:
#      sql:
#        enabled: true
#        database-name: wfrp
#        instance-connection-name: wfrp-helper:europe-west3:wfrp
#      credentials:
#        location: file:e:/java/gcp/wfrp-helper-fd665e0fc547.json

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        dialect: pl.khuzzuk.wfrp.helper.common.PostgresqlDialect
        jdbc:
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
    open-in-view: false
  flyway:
    locations: classpath:/db/migration,/db/data

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationSeconds: 14400
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

logging:
  level:
    root: info
