server:
  port: 1081

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/wfrp
    username: wfrp
    password: wfrp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  flyway:
    locations: classpath:/db/migration,/db/data
