server:
  port: 1081

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/wfrp
    username: wfrp
    password: wfrp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        dialect: pl.khuzzuk.wfrp.helper.common.PostgresqlDialect
        jdbc:
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  flyway:
    locations: classpath:/db/migration,/db/data

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationSeconds: 14400
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect