server:
#  port: 1081
  servlet:
    session:
      timeout: 60m

spring:
  application:
    name: wfrp-helper
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 438518771997-jv58q8ru6tjqq18sgu018rn1656k4oja.apps.googleusercontent.com
            client-secret: cR_quZ1S9CElInxDyJu7rtFm
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
  datasource:
    url: jdbc:postgresql://localhost:5432/wfrp
    username: wfrp
    password: wfrp
    driver-class-name: org.postgresql.Driver
#  cloud:
#    gcp:
#      sql:
#        enabled: true
#        database-name: wfrp
#        instance-connection-name: wfrp-helper:europe-west3:wfrp
#      credentials:
#        location: file:e:/java/gcp/wfrp-helper-fd665e0fc547.json

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        dialect: pl.khuzzuk.wfrp.helper.common.PostgresqlDialect
        jdbc:
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://localhost:8090

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationSeconds: 14400
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
