export enum DeterminantType {
    SPEED = 'SPEED',
    BATTLE = 'BATTLE',
    SHOOTING = 'SHOOTING',
    STRENGTH = 'STRENGTH',
    DURABILITY = 'DURABILITY',
    HEALTH = 'HEALTH',
    INITIATIVE = 'INITIATIVE',
    ATTACK = 'ATTACK',
    DEXTERITY = 'DEXTERITY',
    LEADER_SKILLS = 'LEADER_SKILLS',
    INTELLIGENCE = 'INTELLIGENCE',
    CONTROL = 'CONTROL',
    WILL = 'WILL',
    CHARISMA = 'CHARISMA',
    PARRY = 'PARRY',
    OPPONENT_PARRY = 'OPPONENT_PARRY',
}

export const creatureDeterminants = [
    DeterminantType.SPEED,
    DeterminantType.BATTLE,
    DeterminantType.SHOOTING,
    DeterminantType.STRENGTH,
    DeterminantType.DURABILITY,
    DeterminantType.HEALTH,
    DeterminantType.INITIATIVE,
    DeterminantType.ATTACK,
    DeterminantType.DEXTERITY,
    DeterminantType.LEADER_SKILLS,
    DeterminantType.INTELLIGENCE,
    DeterminantType.CONTROL,
    DeterminantType.WILL,
    DeterminantType.CHARISMA,
];

export const percentDeterminants = [
    DeterminantType.BATTLE,
    DeterminantType.SHOOTING,
    DeterminantType.INITIATIVE,
    DeterminantType.DEXTERITY,
    DeterminantType.LEADER_SKILLS,
    DeterminantType.INTELLIGENCE,
    DeterminantType.CONTROL,
    DeterminantType.WILL,
    DeterminantType.CHARISMA,
    DeterminantType.PARRY,
    DeterminantType.OPPONENT_PARRY,
];
