export enum FieldType {
    TEXT = 'TEXT',
    TEXT_AREA = 'TEXT_AREA',
    TEXT_ARRAY = 'TEXT_ARRAY',
    INTEGER = 'INTEGER',
    FLOAT = 'FLOAT',
    BOOLEAN = 'BOOLEAN',
    ENTITY_SELECT = 'ENTITY_SELECT',
    ENTITY_MULTISELECT = 'ENTITY_MULTISELECT',
    ENUM_MULTISELECT = 'ENUM_MULTISELECT',
    DETERMINANT = 'DETERMINANT',
}