INSERT INTO world.nation (name, description)
VALUES ('Imperium', 'Najpotężniejsze państwo ludzi w Starym Świecie. Zostało założone przez Sigmara Młotodzierżce. Rządzone jest przez Imperatora. Aktualnym władcą jest Karl Franz, zaś jego stolicą- Altdorf.'),
       ('Laurelorn', 'Las Laurelorn leży na północnym wybrzeżu Imperium i jest zamieszkany przez samotne społeczności Eonirów. Chociaż zarówno Middenland, jak i Nordland, wysuwają roszczenia wobec lasu Laurelorn, Eonirowie wciąż pozostają niezależnym ludem. Laurelorn znajduje się na zachód od Salzenmund i górujących nad nim Srebrnych Wzgórz. Sięga dalej na zachód aż do granic Jałowej Krainy.'),
       ('Bretonia', 'Bretonia jest dużym feudalnym królestwem wzorowanym na Arturiańskiej Brytanii i Francji, które zostało stworzone z grupy miast przez Gilles''a Le Breton''a na polecenie Pani Jeziora, która później stała się patronką Bretoni. Bretonia jest po Imperium najpewniej drugim co do potęgi krajem w Starym Świecie. Surowy system klasowy sprawia, że tylko wyższe klasy są wyedukowane i uczone w duchu rycerskości. Niższe klasy składają się w większości z uciskanych chłopów. Odrzuciwszy technikę tworzenia czarnego prochu Bretończycy skupili się na tradycyjnym stylu walki konnej używając piechoty i łuczników jako wsparcia. Kultura Bretoni wzorowana jest na średniowiecznej Francji – podobny jest język, nazwy miast, herby i godła, a tożsamość kraju, podobnie jak jego wizerunek wśród innych ludów Starego Świata, koncentruje się wokół jednego pojęcia: rycerstwo.'),
       ('Kislev', 'Kislev jest szeroko znany za swoje wybitnie niskie temperatury i jest najbardziej wysuniętym na północ krajem Starego Świata. Rządzą nim Carowie i Królowa Lodu. Jako kraj graniczy musi znosić najwięcej potyczek i walk z Chaosem. Erengrad, Kislev (stolica) i Praag są trzema największymi miastami Kisleva, z Erengradem i Praag usytuowanymi nad największą rzeką Lynsk. Kislev został założony około tysiąca lat po Imperium przez Gospodarów i plemiona Ungołów. Ich bóstwem jest Ursun, ojciec niedźwiedzi.'),
       ('Tilea', 'Tilea jest podzielona pomiędzy największe rywalizujące miasta-państwa: Remas, Trantio, Miragliano, Luccini i Verezzo. Tileańczycy znani są jako niezwykle utalentowani handlarze i są w stanie wytargować wszystko na swoją korzyść oprócz Arabów , którzy wytrenowali tą sztukę do perfekcji znajdując idealny rynek zbytu w Tilei. Większość wojsk w tym kraju stanowią najemnicy z całego Starego Świata a ich żołd jest niemal przysłowiowy.'),
       ('Estalia', 'Estalia jest luźno wzorowana na Hiszpanii i jest podzielona na rywalizujące ze sobą miasta takie jak Magritta i Tobraro. Estalijczycy żywią wielkie urazy za błędy Tileańczyków i vice versa. Estalijska stal jest sławna w całym Starym Świecie za swą jakość. Kraj ten został podbity przez Sułtana Arabii a w wyniku tego w konflikcie wzięły udział tak dalekie kraje jak Imperium czy Bretonia.'),
       ('Księstwa graniczne', 'Księstwa Graniczne są luźnym zbitkiem miast i osad na dalekim południu Starego Świata, stanowiące jego granice i będące częstym celem ataków Zielonoskórych, Zwierzoludzi i innych dzikich ras. Wiele Psów Wojny wywodzi się z tamtąd.'),
       ('Marienburg', 'Marienburg jest tętniącym życiem miastem-państwem Jałowych Ziem, które pokojowo odłączyło się od Imperium jakiś czas temu. Marienburg jest jednym z największych miast w Starym Świecie, opływającym w towary przywożone zza Wielkiego Oceanu, Morza Szponów, czy spławiane rzeką Reik płynącą przez Nuln i Altdorf.'),
       ('Sartosa', 'Sartosa jest małą wyspa na południe od brzegów Tilei. Sartosą rządzą królowie-piraci, którzy stworzyli królestwo będące rajem dla piratów i innych kryminalistów. Piraci często atakują i łupią przybrzeżne osady, choć też czasem ich bronią.');